In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
bike_data = pd.read_csv('../../datasets/bike_sharing_hourly.csv', index_col=0)
bike_data.head(10)

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,,
1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,0.0896,0,1,1
7,2011-01-01,1,0,1,6,0,6,0,1,0.22,0.2727,0.80,0.0000,2,0,2
8,2011-01-01,1,0,1,7,0,6,0,1,0.20,0.2576,0.86,0.0000,1,2,3
9,2011-01-01,1,0,1,8,0,6,0,1,0.24,0.2879,0.75,0.0000,1,7,8
10,2011-01-01,1,0,1,9,0,6,0,1,0.32,0.3485,0.76,0.0000,8,6,14

In [ ]:
bike_data[['temp', 'hum']].describe()

In [ ]:
bike_data[['temp', 'hum']].corr()

In [ ]:
bike_data['temp'].autocorr(lag=2)

In [ ]:
bike_data['temp'].autocorr(lag=12)

In [ ]:
bike_data['temp'].autocorr(lag=102)

In [ ]:
bike_data['temp'].autocorr(lag=1002)

In [ ]:
bike_data['hum'].autocorr(lag=2)

In [ ]:
bike_data['temp'].autocorr(lag=1)

In [ ]:
fig, (ax1, ax2) = plt.subplots(2,1,figsize=(12,14))

ax1.acorr(bike_data['temp'],
          maxlags=12,color='green')

ax1.title.set_text('Temperature')
ax1.set_xlabel('Lags', fontsize=15)

ax2.acorr(bike_data['hum'],
          maxlags=12, color='red')

ax2.title.set_text('Humidity')
ax2.set_xlabel('Lags', fontsize=15)
plt.show();

In [ ]:
fig, (ax1, ax2) = plt.subplots(1,2,figsize=(20,8))

ax1.acorr(bike_data['temp'],
          maxlags=24,color='deeppink')

ax1.title.set_text('Temperature')
ax1.set_xlabel('Lags', fontsize=12)

ax2.acorr(bike_data['hum'],
          maxlags=24, color='blue')

ax2.title.set_text('Humidity')
ax2.set_xlabel('Lags', fontsize=12)

plt.suptitle('Autocorrelation')

plt.show();